# Generated by Django 4.1.7 on 2023-03-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='images',
        ),
    ]
