# Generated by Django 4.1.7 on 2023-03-16 08:07

from django.db import migrations, models
import gallery.utils


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, unique=True, upload_to=gallery.utils.video_upload_path),
        ),
    ]
