# Generated by Django 4.1.7 on 2023-03-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_image_managers_alter_imagegallery_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='image',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='imagegallery',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='video',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='videogallery',
            managers=[
            ],
        ),
    ]
