# Generated by Django 4.1.7 on 2023-03-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_imagegallery_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='gallery_name',
            field=models.CharField(max_length=200),
        ),
    ]
